# theme: jekyll-theme-hacker
# Site
title: X社區的秘密


# 網頁計數器
# Show PV/UV of the website/page with busuanzi.
# Get more information on   http://ibruce.info/2015/04/04/busuanzi/
busuanzi_count:
# count values only if the other configs are false
enable: true
# custom uv span for the whole site
site_uv: true
site_uv_header: 
site_uv_footer: 
# custom pv span for the whole site
site_pv: true
site_pv_header: 
site_pv_footer:
# custom pv span for one page only
page_pv: true
page_pv_header: 
page_pv_footer:
