theme: jekyll-theme-hacker
# Site
title: X社區的秘密

# Show PV/UV of the website/page with busuanzi.
# Get more information on   http://ibruce.info/2015/04/04/busuanzi/
busuanzi_count:
# count values only if the other configs are false
enable: true
# custom uv span for the whole site
site_uv: true
site_uv_header: <i class="fa fa-user"></i>
site_uv_footer: 
# custom pv span for the whole site
site_pv: true
site_pv_header: <i class="fa fa-eye"></i>
site_pv_footer:
# custom pv span for one page only
page_pv: true
page_pv_header: <i class="fa fa-file-o"></i>
page_pv_footer:

作者：豆沙包o小白
链接：https://www.jianshu.com/p/7461895ed177
來源：简书
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
